spring:
    application:
        name : SP_CURD_APP

    # MySQL DataSource Configuration
    datasource:
        url : ${DB_URL}
        username : ${DB_USERNAME}
        password : ${DB_PASSWORD}
        driver-class-name : com.mysql.cj.jdbc.Driver

    # HikariCP Connection Pool
        hikari:
            maximum-pool-size : 10
            minimum-idle : 5
            connection-timeout : 20000
            idle-timeout : 300000
            max-lifetime : 1200000

    # Hibernate/JPA Configuration
    jpa:
        hibernate:
            ddl-auto : update
        show-sql : true
        database-platform: org.hibernate.dialect.MySQLDialect
        properties:
            hibernate:
                format_sql : true
